runtime: java17
entrypoint: 'java -jar weatherify-api-all.jar'

readiness_check:
  path: /
  check_interval_sec: 5
  timeout_sec: 2
  failure_threshold: 2

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2

env_variables:
  GCP_PROJECT_ID: "1017382896100"
  DB_NAME: "weatherify-app-db"
  WEATHER_URL: "https://api.openweathermap.org/data/3.0/onecall"
  AIR_POLLUTION_URL: "https://api.openweathermap.org/data/2.5/air_pollution"
  JWT_EXPIRATION: "3600000"
  JWT_AUDIENCE: "jwt-audience"
  JWT_ISSUER: "jwt-issuer"
  JWT_REALM: "jwt-realm"
