package util

object Constants {
    object Database {
        const val DEFAULT_DB_NAME = "weather"
        const val FEEDBACK_COLLECTION = "feedback"
        const val USERS_COLLECTION = "users"
        const val SAVED_LOCATIONS_COLLECTION = "saved_locations"
        const val PAYMENTS_COLLECTION = "payments"
        const val REFUNDS_COLLECTION = "refunds"
        const val TRIPS_COLLECTION = "trips"
        const val NOTES_COLLECTION = "notes"
        const val ID_FIELD = "_id"
        const val EMAIL_FIELD = "email"
    }

    object Auth {
        const val DEFAULT_JWT_REALM = "jwt-realm"
        const val DEFAULT_JWT_ISSUER = "jwt-issuer"
        const val DEFAULT_JWT_AUDIENCE = "jwt-audience"
        const val DEFAULT_JWT_EXPIRATION = "3600000"
        const val JWT_CLAIM_EMAIL = "email"
        const val JWT_CLAIM_ROLE = "role"
        const val JWT_SECRET_NAME = "jwt-secret"
        const val DB_CONNECTION_STRING_SECRET = "db-connection-string"
        const val RAZORPAY_SECRET = "razorpay-secret"
        const val RAZORPAY_KEY_ID = "razorpay-key-id"
        const val RAZORPAY_WEBHOOK_SECRET = "razorpay-webhook-secret"
        const val SENDGRID_API_KEY = "sendgrid-api-key"
        const val FIREBASE_SERVICE_ACCOUNT_KEY = "firebase-service-account-key"
        const val INVALID_EMAIL_FORMAT = "Invalid email format"
        const val INVALID_PASSWORD_STRENGTH =
            "Password must be at least 8 characters long and contain uppercase, lowercase, digit, and at least one special character (!@#$%^&*()_-+=<>?/[]{}|)"
    }

    object Api {
        const val WEATHER_ENDPOINT = "/weather"
        const val FEEDBACK_ENDPOINT = "/feedback"
        const val LOGIN_ENDPOINT = "/login"
        const val REGISTER_ENDPOINT = "/register"
        const val REFRESH_TOKEN_ENDPOINT = "/refresh-token"
        const val LOGOUT_ENDPOINT = "/logout"
        const val HOME_ENDPOINT = "/"
        const val CREATE_ORDER_ENDPOINT = "/create-order"
        const val STORE_PAYMENT_ENDPOINT = "/store-payment"
        const val NOTES_ENDPOINT = "/notes"
        const val DEFAULT_WEATHER_URL = "https://api.openweathermap.org/data/3.0/onecall"
        const val DEFAULT_AIR_POLLUTION_URL = "https://api.openweathermap.org/data/2.5/air_pollution"
        const val PARAM_LAT = "lat"
        const val PARAM_LON = "lon"
        const val PARAM_APP_ID = "appid"
        const val PARAM_EXCLUDE = "exclude"
        const val PARAM_ID = "id"
        const val PARAM_DEVICE_ID = "deviceId"
        const val PARAM_DEVICE_OS = "deviceOs"
        const val PARAM_FEEDBACK_TITLE = "feedbackTitle"
        const val PARAM_FEEDBACK_DESCRIPTION = "feedbackDescription"
        const val EXCLUDE_MINUTELY = "minutely"
    }

    object Messages {
        const val REGISTRATION_SUCCESS = "User registered successfully"
        const val LOGIN_SUCCESS = "Login successful"
        const val TOKEN_REFRESH_SUCCESS = "Token refreshed successfully"
        const val TOKEN_NOT_EXPIRED = "Token is still valid and does not need to be refreshed"
        const val TOKEN_INVALID = "Invalid token provided for refresh"
        const val INVALID_CREDENTIALS = "Invalid email or password"
        const val USER_ALREADY_EXISTS = "User already exists"
        const val FAILED_REGISTER = "Failed to register user"
        const val USER_NOT_REGISTERED = "Invalid email or password"
        const val ACCOUNT_INACTIVE = "Account is inactive"
        const val LOGOUT_SUCCESS = "Logged out successfully"
        const val FEEDBACK_SUBMITTED = "Feedback submitted successfully"
        const val FEEDBACK_RETRIEVED = "Feedback retrieved successfully"
        const val FEEDBACK_NOT_FOUND = "Feedback not found"
        const val FEEDBACK_REMOVED = "Feedback removed successfully"
        const val FEEDBACK_REMOVAL_FAILED = "Feedback not found or could not be removed"
        const val FAILED_SAVE_FEEDBACK = "Failed to save feedback"
        const val NOTE_CREATED = "Note created successfully"
        const val NOTE_UPDATED = "Note updated successfully"
        const val NOTES_RETRIEVED = "Notes retrieved successfully"
        const val NOTE_NOT_FOUND = "Note not found"
        const val NOTE_EMPTY_ERROR = "Note content cannot be empty"
        const val FAILED_CREATE_NOTE = "Failed to create note"
        const val FAILED_UPDATE_NOTE = "Failed to update note"
        const val WEATHER_RETRIEVED = "Weather data retrieved successfully"
        const val FAILED_FETCH_WEATHER = "Failed to fetch weather data"
        const val MISSING_LOCATION_PARAMS = "Missing mandatory query parameters: lat and lon"
        const val INTERNAL_SERVER_ERROR = "Internal server error"
        const val DATABASE_ERROR = "Database operation failed"
        const val AUTHENTICATION_ERROR = "Authentication process failed"
        const val VALIDATION_ERROR = "Validation process failed"
        const val NETWORK_ERROR = "Network operation failed"
        const val UNKNOWN_ERROR = "An unexpected error occurred"
        const val ENDPOINT_NOT_FOUND = "The requested endpoint does not exist"
    }

    object Env {
        const val JWT_EXPIRATION = "JWT_EXPIRATION"
        const val JWT_AUDIENCE = "JWT_AUDIENCE"
        const val JWT_ISSUER = "JWT_ISSUER"
        const val JWT_REALM = "JWT_REALM"
        const val DB_NAME = "DB_NAME"
        const val WEATHER_URL = "WEATHER_URL"
        const val AIR_POLLUTION_URL = "AIR_POLLUTION_URL"
        const val GA_MEASUREMENT_ID = "GA_MEASUREMENT_ID"
        const val GA_API_SECRET = "GA_API_SECRET"
        const val GA_ENABLED = "GA_ENABLED"
        const val FROM_EMAIL = "FROM_EMAIL"
        const val FROM_NAME = "FROM_NAME"
        const val GCP_PROJECT_ID = "GCP_PROJECT_ID"
    }
}
