name: Auto Deploy on Main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 468.0.0'

      - name: Submit Cloud Build (build + deploy, no promote)
        run: |
          gcloud builds submit \
            --project "${{ secrets.GCP_PROJECT_ID }}" \
            --config=cloudbuild.yaml \
            --substitutions=_DEPLOY="true",_PROMOTE="false",_APP_YAML="src/main/appengine/app.yaml" \
            .
